baseURL = "https://ryanigans.com/blog/"
languageCode = 'en-us'
title = 'ryanigans'
theme = "hextra"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  [params.navbar]
    displayTitle = true
  [params.sidebar]
    defaultOpen = true
    displayEmpty = false # Set to true if you want to see folders even if empty